version: "3.8"

services:
  redis-smp:
    image: docker-registry-002.zeuslearning.com/zeuslearning/redis:7-alpine
    container_name: redis-smp
    ports:
      - "6379:6379"
    volumes: 
      - redis-data-smp:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  rabbitmq-smp:
    image: docker-registry-002.zeuslearning.com/zeuslearning/rabbitmq:3.13.7-management
    container_name: rabbitmq-smp
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq-lib-smp:/var/lib/rabbitmq/
      - rabbitmq-log-smp:/var/log/rabbitmq


volumes:
  redis-data-smp:
    driver: local
  rabbitmq-lib-smp:
    driver: local
  rabbitmq-log-smp:
    driver: local